### ISSUE TITLE
Doesn't work anymore in phone

### ISSUE THREAD

**Issue by costales** [bittner/appear-in#3]
Hi, please, could you update the user agent?

https://lists.launchpad.net/ubuntu-phone/msg23294.html

Thanks!

**Comment by bittner** [comment]
I'm not sure whether you're confusing things here. But maybe I misunderstand.

The webapp-container used by this app can override user-agent, but how should this change things? We can try [as suggested](https://lists.launchpad.net/ubuntu-phone/msg23292.html), but I can't promise anything.

Does it work in the phone browser when you type in https://appear.in/test-drive ?

**Comment by bittner** [comment]
Released [version 0.4](https://uappexplorer.com/app/appear-in.peter-bittner) in the Ubuntu Store.

Can you try whether the app now works as expected?

**Comment by costales** [comment]
Versión 0.4: Enter a room and empty webview.

In browser: https://appear.in/test-drive empty webview too.

Thanks in advance!

**Comment by bittner** [comment]
If your phone's web browser doesn't show the appear.in website, neither partially nor fully, I'm afraid there's nothing I can do about it. Then this needs to be fixed either by Canonical (in the web browser code), or by the Appear.in team (in their web application code), or by both.

**Comment by costales** [comment]
It was working ~2 months ago, just FYI

**Comment by bittner** [comment]
Sure. In the meantime, let me guess, there was an OTA upgrade of Ubuntu Touch. And most evidently, Appear.in made heavy changes to their application.

It's a pain. I'm sorry. But my hands are tied.

Are you sure it's not even working in the phone browser? Maybe you could try to clean the cache?

**Comment by gurucubano** [comment]
I have three BD E4.5, all with the latest OTA-14. On one I had installed
appear-in (the older version) and updated(!) it yesterday to version 0.4. 
This worked now between the BQ and a browser firefox in my netbook (at
least I could see the picture from the cam of the BQ in the FF, the
laptop had no cam configured and I was to lazy at night).

I installed(!) version 0.4 now in the two other BQ devices and when I
enter a room name, both switch to a white display, nothing more, no
question about the access to the cam or mic.

I wild guess is, that in the new version something is missing, which is
in the first BQ device because it was updated. But this is only a wild
guess._
![appear-in-01](https://cloud.githubusercontent.com/assets/8157672/22173867/378b42f4-dfcf-11e6-9a55-aacca1d4b238.png)

**Comment by gurucubano** [comment]
Let's make a test: please give me the older click package (the one before 0.4), I will deinstall 0.4, install the older and update again to 0.4; let's see if this works, and then look what is causing the fault;

**Comment by bittner** [comment]
Commit https://github.com/bittner/appear-in/commit/6794783a076862b101ab3ad92b873be2570df4d1 shows the changes from version 0.3 to 0.4. There's nothing fabulous that changed.

You should be able to edit [the desktop file](https://github.com/bittner/appear-in/blob/master/appear-in.desktop) on your phone. See [this AskUbuntu question](http://askubuntu.com/questions/602850/how-do-i-backup-my-ubuntu-phone) for the folders where you can find the installed apps. According to my experience the cache should be emptied though, to make certain problems related to `webapp-container` go away.

Don't hope too much, though. Voice and video worked before, and if it's broken it's really either Canonical's merit (it got partly better, partly worse with every OTA) or the one of [the Appear.in team](https://appear.in/information/team/), or both. See issue #1 (visit every single link mentioned) if you need to be entertained.  :roll_eyes: :scream_cat:

**Comment by bittner** [comment]
This may be related: "[[OTA14] App permission issue](https://lists.launchpad.net/ubuntu-phone/msg23279.html)" (ubuntu-phone mailing list)

**Comment by gurucubano** [comment]
more observations:
1. I installed version 0.4.(also for the 1st time) on my M10, same problem there; 
2. when I go with the browser directly to https://appear.in/ and enter my root 'gurucubano', gives empty window;
3. on the BQ E4.5 where the web-app works fine, when I use there the browser going to https://appear.in/ and entering the room, gives empty window;

the 3rd proofes, that there must be something magic in the the desktop file of the web-app (maybe the UserAgent string) which makes it work, but not in the browser directly;

**Comment by bittner** [comment]
@gurucubano Take a look at the desktop file, as I said: There is absolutely no magic in there.

[Take a look at it](https://github.com/bittner/appear-in/blob/master/appear-in.desktop#L6):

- The `webapp-container` in the `Exec=` line is a binary that is shipped with the `webbrowser-app`, which gives [(apparmor-) limited access](https://github.com/bittner/appear-in/blob/master/appear-in.apparmor) to the capabilities of the webbrowser-app.
- Yet still, it's _just the same as the phone browser_, technically, a full-screen viewport of it, if you want so.
- If the behavior between `webbrowser-app` and `webapp-container` is different it must be due to either the app permissions (apparmor) or some of the command line parameters passed to `webapp-container` (`--user-agent-string` is one of them, true).

If you run a website with your phone's web browser and it doesn't work, it won't work in any `webapp-container` (with the exception of websites reacting to the `user-agent-string` and similar stuff). Simply because that is an un-restricted, un-apparmor'ed execution of the same thing (the `webapp-container` runs the same code as the web browser, but with restrictions you can lift selectively as a developer).

So again, if the Appear.in WebApp has stopped working on the phone, go shout at Canonical and/or the Appear.in team. One of them, or both in parallel, have broken the experience. (The [log output](http://paste.ubuntu.com/23838449/) you mention [on the mailing list](https://lists.launchpad.net/ubuntu-phone/msg23384.html) indicates a _"bad HTTP response code (403)"_ - `Forbidden` - and _"An AppArmor policy"_ causing QML/JS to abort execution.)

If the browser (or the website) is broken there is absolutely nothing I can do about it: **The Appear.in WebApp is a dumb desktop shortcut that calls a binary Canonical provides.**

**Comment by gurucubano** [comment]
New observation: on the (only) BQ where the web-app is working, I can only 
use the room 'gurucubano' which was created in the past with v 0.3, I can 
not use/create any other room;

and this works fine, I run a conf with someone with FF on Windows;

but on the same BQ in the we-browser https://appear.in/gurucubano is NOT 
working; why is the web-app working, but the browser is not?

and why is the web-app only working with the  old room?

A general word: it does not help to blame Canonical or the Appear.in team, 
if you/we think there is some fault, we should help to nail it down.

Matthias



-- 
Sent from my Ubuntu phone
http://www.unixarea.de/

**Comment by bittner** [comment]
> why is the web-app working, but the browser is not?

This is most probably due to the `--user-agent-string` (mimicking a desktop Chromium browser).

> and why is the web-app only working with the  old room?

This is probably an issue with Appear.in's website implementation (their JavaScript). Maybe in combination with changes to oxide in the last OTA.

> if you/we think there is some fault, we should help to nail it down.

I agree. Sit down with Canonical and analyse your logs. Sit down with Appear.in and analyse your logs. This is the wrong place, though (at least for talking to Canonical staff the mailing list and IRC are better).

Don't Read This  :weary: :smirk: :flushed:
--------------
I've got limited hope, though, to see this getting work properly. With Canonical it actually got _worse_ with every OTA. Maybe with @appearin expressing interest in putting this issue on the table together with @CanonicalLtd this could change. But seriously, Ubuntu (Touch) is such a marginal nice market, even for them. It's almost a shame.

**Comment by bittner** [comment]
Putting @ingridod from @appearin on Cc to let them know about this issue.

**Comment by costales** [comment]
Ping to @oSoMoN too :)

**Comment by gurucubano** [comment]
I have modified the user *.desktop file and set the --user-agent to the value of my FF in my FreeBSD netbook:
...
Exec=webapp-container --store-session-cookies --user-agent-string='Mozilla/5.0 (X11; FreeBSD amd64; rv:43.0) Gecko/20100101 Firefox/43.0' --webappUrlPatterns=https?://appear.in/*,https?://*.appear.in/* https://appear.in/ %u

this makes no difference in the behavior; the room 'gurucubano' is working, while 'gurucubanox' gives only a white page;

I have here the log file ~phablet/.cache/upstart/application-click-appear-in.peter-bittner_appear-in_0.4.log of both session, first the working one for the room 'gurucubano', then the not working one for room 'gurucubanox', in the latter case there is no more log output after entering the room name 'gurucubanox':


[gurucubano.txt](https://github.com/bittner/appear-in/files/721808/gurucubano.txt)

[gurucubanox.txt](https://github.com/bittner/appear-in/files/721809/gurucubanox.txt)


Comments?

**Comment by dagingaa** [comment]
Hi there! 👋 

I'm one of the tech leads for appear.in, @ingridod sent me here. I've tried looking at your issue, and I'm not aware of anything we're doing on our side that hsould cause this issue, let alone between minor versions as well. Looking at the logs from @gurucubano I couldn't decipher anything hat is triggered on our end to get the white page.

One possibility is that this is WebRTC related. If you go to https://webrtc.github.io/samples/src/content/peerconnection/pc1/, does that example work for you end to end?

**Comment by bittner** [comment]
Thanks, @dagingaa, for joining the conversation!

Appear.in used to work on Ubuntu Touch devices, not too bad but always only partly (according to my personal experience). See issue #1 for details.

Would be nice to get your service fully working in UT's browser. Though probably this will have to involve also the Canonical [oxide](https://launchpad.net/oxide) developers. They're best reached [via IRC](https://wiki.ubuntu.com/IRC/ChannelList) (e.g. `#ubuntu-touch`), I believe.

References
------------
- @gurucubano's [ticket on Launchpad](https://bugs.launchpad.net/webbrowser-app/+bug/1658439).
- Some people [on the mailing list report](https://lists.launchpad.net/ubuntu-phone/msg23394.html) that Appear.in works well for them.

**Comment by StuntsPT** [comment]
Ok, so here is my take, on a BQ E4.5.
The last time I used v0.3, it was on new year's eve. Everything was working back then. This was already on the latest OTA14, so I don't think anything else changed on my end after that.

@bittner I have now tried v0.3, v0.4 and the Ubuntu-touch browser, and on all accounts I get the "white screen". I have tried to create a room on my laptop's browser (Firefox) and join that room on my Ubuntu-touch device. Nothing is reported in the test room, as someone joining.

@dagingaa - Thank you for dropping by! The webrtc sample you provide above works just fine on my Ubuntu-touch device. I can press "Start" and I get to see camera input. Pressing "Call" starts a second camera input. I have to hit "Stop" shortly after due to positive feedback from the mic (which means audio is also working). Was there any change (even if minor) between January 01 and January 17 (which was when this issue was first reported on the ML) that could explain something like this? Maybe some cosmetic changes that somehow "Oxide" (the web browser engine for Ubuntu-touch) can't handle. What sort of logs could be of interest for you?

**Comment by gurucubano** [comment]
On Monday, 23 January 2017 22:52:40 CET, Dag-Inge Aas 
<notifications@github.com> wrote:
> Hi there! 👋 
> 
> I'm one of the tech leads for appear.in, @ingridod sent me 
> here. I've tried looking at your issue, and I'm not aware of 
> anything we're doing on our side that hsould cause this issue, 
> let alone between minor versions as well. Looking at the logs 
> from @gurucubano I couldn't decipher anything hat is triggered 
> on our end to get the white page.
> 
> One possibility is that this is WebRTC related. If you go to 
> https://webrtc.github.io/samples/src/content/peerconnection/pc1/, 
> does that example work for you end to end?
> 

Yes, works for me on BQ E4.5. Thanks for jumping on.

matthias



-- 
Sent from my Ubuntu phone
http://www.unixarea.de/

**Comment by gurucubano** [comment]
I have just tested another WebRTC based (OpenSource) service with my BQ E4.5 OTA-14: 
https://hubl.in/room-name
and did a video conf between 4 parties; this just worked fine and out of the box;

**Comment by gurucubano** [comment]
@dagingaa : I do not think that the white screen problem is webRTC related because the browser does not even ask perms to access the mic and cam in this case;

**Comment by oSoMoN** [comment]
Thanks everyone for the investigation. It appears the issue is in fact https://launchpad.net/bugs/1656551, which an oxide update will fix (due in OTA-15).

**Comment by dagingaa** [comment]
Glad to hear we didn't break anything at least! Thanks for figuring out this issue :) even though the usage might be small, we try to at the very least present something to every modern browser. A white page would be very bad

**Comment by StuntsPT** [comment]
Fixed in OTA-15.

**Comment by bittner** [comment]
@StuntsPT Thanks for letting us know!

**Comment by gurucubano** [comment]
El día Tuesday, February 07, 2017 a las 05:31:26AM -0800, Francisco Pina-Martins escribió:

> Fixed in OTA-15.

ACK.

	matthias

-- 
Matthias Apitz, ✉ guru@unixarea.de, ⌂ http://www.unixarea.de/  ☎ +49-176-38902045
